using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WordsmithHub.Domain;

namespace WordsmithHub.Infrastructure.MainDatabase.Configurations;

public class DomainTypeConfiguration : IEntityTypeConfiguration<DomainType>
{
    public void Configure(EntityTypeBuilder<DomainType> builder)
    {
        builder.ToTable("DomainTypes");
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).IsRequired().ValueGeneratedNever();
        builder.Property(c => c.Name).IsRequired().HasMaxLength(50);
        builder.Property(c => c.Code).IsRequired().HasMaxLength(40);
        // Seed data
        builder.HasData(
            new DomainType { Id = 1, Name = "Administration", Code = "administration" },
            new DomainType { Id = 2, Name = "Administration publique", Code = "publicAdministration" },
            new DomainType { Id = 3, Name = "Aéronautique", Code = "aeronautics" },
            new DomainType { Id = 4, Name = "Agriculture", Code = "agriculture" },
            new DomainType { Id = 5, Name = "Architecture", Code = "architecture" },
            new DomainType { Id = 6, Name = "Arts", Code = "arts" },
            new DomainType { Id = 7, Name = "Arts appliqués", Code = "appliedArts" },
            new DomainType { Id = 8, Name = "Arts du spectacle", Code = "performingArts" },
            new DomainType { Id = 9, Name = "Arts plastiques", Code = "visualArts" },
            new DomainType { Id = 10, Name = "Assurances", Code = "insurance" },
            new DomainType { Id = 11, Name = "Astronautique", Code = "astronautics" },
            new DomainType { Id = 12, Name = "Astronomie", Code = "astronomy" },
            new DomainType { Id = 13, Name = "Audiovisuel", Code = "audiovisual" },
            new DomainType { Id = 14, Name = "Automobile", Code = "automotive" },
            new DomainType { Id = 15, Name = "Banque", Code = "banking" },
            new DomainType { Id = 16, Name = "BD et manga", Code = "comicsManga" },
            new DomainType { Id = 17, Name = "Beaux-arts", Code = "fineArts" },
            new DomainType { Id = 18, Name = "Biologie", Code = "biology" },
            new DomainType { Id = 19, Name = "Botanique", Code = "botany" },
            new DomainType { Id = 20, Name = "Carrières", Code = "quarrying" },
            new DomainType { Id = 21, Name = "Chaudronnerie", Code = "boilermaking" },
            new DomainType { Id = 22, Name = "Chimie", Code = "chemistry" },
            new DomainType { Id = 23, Name = "Chimie du pétrole", Code = "petrochemistry" },
            new DomainType { Id = 24, Name = "Chirurgie", Code = "surgery" },
            new DomainType { Id = 25, Name = "Cinéma", Code = "cinema" },
            new DomainType { Id = 26, Name = "Commerce", Code = "commerce" },
            new DomainType { Id = 27, Name = "Comptabilité", Code = "accounting" },
            new DomainType { Id = 28, Name = "Construction", Code = "construction" },
            new DomainType { Id = 29, Name = "Cryptomonnaies", Code = "crypto" },
            new DomainType { Id = 30, Name = "Cuisine et gastronomie", Code = "gastronomy" },
            new DomainType { Id = 31, Name = "Culture", Code = "culture" },
            new DomainType { Id = 32, Name = "Cybernétique", Code = "cybernetics" },
            new DomainType { Id = 33, Name = "Cybersécurité", Code = "cybersecurity" },
            new DomainType { Id = 34, Name = "Démographie", Code = "demography" },
            new DomainType { Id = 35, Name = "Dentisterie", Code = "dentistry" },
            new DomainType { Id = 36, Name = "Droit administratif", Code = "administrativeLaw" },
            new DomainType { Id = 37, Name = "Droit commercial", Code = "commercialLaw" },
            new DomainType { Id = 38, Name = "Droit constitutionnel", Code = "constitutionalLaw" },
            new DomainType { Id = 39, Name = "Droit et justice", Code = "lawJustice" },
            new DomainType { Id = 40, Name = "Droit international", Code = "internationalLaw" },
            new DomainType { Id = 41, Name = "Droit judiciaire", Code = "judicialLaw" },
            new DomainType { Id = 42, Name = "Droit minier", Code = "miningLaw" },
            new DomainType { Id = 43, Name = "Droit pénal", Code = "criminalLaw" },
            new DomainType { Id = 44, Name = "Droit privé", Code = "privateLaw" },
            new DomainType { Id = 45, Name = "Droit social", Code = "socialLaw" },
            new DomainType { Id = 46, Name = "Écologie", Code = "ecology" },
            new DomainType { Id = 47, Name = "Économie", Code = "economics" },
            new DomainType { Id = 48, Name = "Éducation", Code = "education" },
            new DomainType { Id = 49, Name = "Éducation physique et sportive", Code = "physicalEducation" },
            new DomainType { Id = 50, Name = "Électricité", Code = "electricity" },
            new DomainType { Id = 51, Name = "Électronique", Code = "electronics" },
            new DomainType { Id = 52, Name = "Élevage", Code = "animalFarming" },
            new DomainType { Id = 53, Name = "Emballages", Code = "packaging" },
            new DomainType { Id = 54, Name = "Énergies", Code = "energies" },
            new DomainType { Id = 55, Name = "Énergies renouvelables", Code = "renewableEnergy" },
            new DomainType { Id = 56, Name = "Environnement", Code = "environment" },
            new DomainType { Id = 57, Name = "Équipement médico-chirurgical", Code = "medicalEquipment" },
            new DomainType { Id = 58, Name = "Exploitation minière", Code = "mining" },
            new DomainType { Id = 59, Name = "Extraction du pétrole et du gaz naturel", Code = "oilGasExtraction" },
            new DomainType { Id = 60, Name = "Finances", Code = "finance" },
            new DomainType { Id = 61, Name = "Géographie", Code = "geography" },
            new DomainType { Id = 62, Name = "Géologie", Code = "geology" },
            new DomainType { Id = 63, Name = "Gestion de l'entreprise", Code = "businessManagement" },
            new DomainType { Id = 64, Name = "Gestion du personnel", Code = "hrManagement" },
            new DomainType { Id = 65, Name = "Histoire", Code = "history" },
            new DomainType { Id = 66, Name = "Hôtellerie", Code = "hospitality" },
            new DomainType { Id = 67, Name = "Imagerie médicale", Code = "medicalImaging" },
            new DomainType { Id = 68, Name = "Immobilier", Code = "realEstate" },
            new DomainType { Id = 69, Name = "Industrie", Code = "industry" },
            new DomainType { Id = 70, Name = "Informatique", Code = "it" },
            new DomainType { Id = 71, Name = "Ingénierie", Code = "engineering" },
            new DomainType { Id = 72, Name = "Intelligence artificielle", Code = "ai" },
            new DomainType { Id = 73, Name = "Jeu vidéo", Code = "videoGame" },
            new DomainType { Id = 74, Name = "Jeux et jouets", Code = "toysGames" },
            new DomainType { Id = 75, Name = "Joaillerie", Code = "jewelry" },
            new DomainType { Id = 76, Name = "Levage", Code = "lifting" },
            new DomainType { Id = 77, Name = "Linguistique", Code = "linguistics" },
            new DomainType { Id = 78, Name = "Littérature", Code = "literature" },
            new DomainType { Id = 79, Name = "Logistique", Code = "logistics" },
            new DomainType { Id = 80, Name = "Lois et documents juridiques", Code = "legalDocuments" },
            new DomainType { Id = 81, Name = "Loisirs", Code = "leisure" },
            new DomainType { Id = 82, Name = "Manutention", Code = "handling" },
            new DomainType { Id = 83, Name = "Marketing", Code = "marketing" },
            new DomainType { Id = 84, Name = "Matériel militaire", Code = "militaryEquipment" },
            new DomainType { Id = 85, Name = "Mathématiques", Code = "mathematics" },
            new DomainType { Id = 86, Name = "Mécanique", Code = "mechanics" },
            new DomainType { Id = 87, Name = "Médecine", Code = "medicine" },
            new DomainType { Id = 88, Name = "Médecine vétérinaire", Code = "veterinaryMedicine" },
            new DomainType { Id = 89, Name = "Métallurgie", Code = "metallurgy" },
            new DomainType { Id = 90, Name = "Météorologie", Code = "meteorology" },
            new DomainType { Id = 91, Name = "Militaire et défense", Code = "defense" },
            new DomainType { Id = 92, Name = "Mines et carrières", Code = "minesQuarries" },
            new DomainType { Id = 93, Name = "Mines métalliques", Code = "metalMining" },
            new DomainType { Id = 94, Name = "Mode et beauté", Code = "fashionBeauty" },
            new DomainType { Id = 95, Name = "Muséologie et patrimoine", Code = "museology" },
            new DomainType { Id = 96, Name = "Musique", Code = "music" },
            new DomainType { Id = 97, Name = "Nucléaire", Code = "nuclear" },
            new DomainType { Id = 98, Name = "Œnologie", Code = "oenology" },
            new DomainType { Id = 99, Name = "Ophtalmologie", Code = "ophthalmology" },
            new DomainType { Id = 100, Name = "Papeterie", Code = "paperIndustry" },
            new DomainType { Id = 101, Name = "Paramilitaire", Code = "paramilitary" },
            new DomainType { Id = 102, Name = "Pédagogie", Code = "pedagogy" },
            new DomainType { Id = 103, Name = "Pétrole", Code = "oil" },
            new DomainType { Id = 104, Name = "Pétrole brut et dérivés", Code = "crudeOilProducts" },
            new DomainType { Id = 105, Name = "Pharmacologie", Code = "pharmacology" },
            new DomainType { Id = 106, Name = "Philosophie et religion", Code = "philosophyReligion" },
            new DomainType { Id = 107, Name = "Photographie", Code = "photography" },
            new DomainType { Id = 108, Name = "Physique", Code = "physics" },
            new DomainType { Id = 109, Name = "Plomberie", Code = "plumbing" },
            new DomainType { Id = 110, Name = "Politique", Code = "politics" },
            new DomainType { Id = 111, Name = "Politiques sociales", Code = "socialPolicies" },
            new DomainType { Id = 112, Name = "Postes", Code = "postalServices" },
            new DomainType { Id = 113, Name = "Prospection minière", Code = "mineralProspecting" },
            new DomainType { Id = 114, Name = "Robotique", Code = "robotics" },
            new DomainType { Id = 115, Name = "Psychologie", Code = "psychology" },
            new DomainType { Id = 116, Name = "Publicité", Code = "advertising" },
            new DomainType { Id = 117, Name = "Raffinage du pétrole", Code = "oilRefining" },
            new DomainType { Id = 118, Name = "Recherche scientifique", Code = "scientificResearch" },
            new DomainType { Id = 119, Name = "Relations publiques", Code = "publicRelations" },
            new DomainType { Id = 120, Name = "Restauration", Code = "restaurantIndustry" },
            new DomainType { Id = 121, Name = "Santé", Code = "health" },
            new DomainType { Id = 122, Name = "Sciences", Code = "science" },
            new DomainType { Id = 123, Name = "Sciences humaines", Code = "humanities" },
            new DomainType { Id = 124, Name = "Sciences naturelles", Code = "naturalSciences" },
            new DomainType { Id = 125, Name = "Sciences politiques", Code = "politicalScience" },
            new DomainType { Id = 126, Name = "Sécurité", Code = "security" },
            new DomainType { Id = 127, Name = "Sécurité incendie", Code = "fireSafety" },
            new DomainType { Id = 128, Name = "Sidérurgie", Code = "steelIndustry" },
            new DomainType { Id = 129, Name = "Sociologie", Code = "sociology" },
            new DomainType { Id = 130, Name = "Sports", Code = "sports" },
            new DomainType { Id = 131, Name = "Sports de combat", Code = "combatSports" },
            new DomainType { Id = 132, Name = "Sports d'équipe", Code = "teamSports" },
            new DomainType { Id = 133, Name = "Sports nautiques", Code = "waterSports" },
            new DomainType { Id = 134, Name = "Stockage", Code = "storage" },
            new DomainType { Id = 135, Name = "Systèmes d'armes", Code = "weaponSystems" },
            new DomainType { Id = 136, Name = "Technologies pétrolières", Code = "petroleumTech" },
            new DomainType { Id = 137, Name = "Télécommunications", Code = "telecom" },
            new DomainType { Id = 138, Name = "Télédétection", Code = "remoteSensing" },
            new DomainType { Id = 139, Name = "Télégraphie", Code = "telegraphy" },
            new DomainType { Id = 140, Name = "Téléphonie", Code = "telephony" },
            new DomainType { Id = 141, Name = "Tourisme", Code = "tourism" },
            new DomainType { Id = 142, Name = "Transport aérien", Code = "airTransport" },
            new DomainType { Id = 143, Name = "Transport par eau", Code = "waterTransport" },
            new DomainType { Id = 144, Name = "Transport par rail", Code = "railTransport" },
            new DomainType { Id = 145, Name = "Transport routier", Code = "roadTransport" },
            new DomainType { Id = 146, Name = "Transports", Code = "transport" },
            new DomainType { Id = 147, Name = "Urbanisme", Code = "urbanPlanning" },
            new DomainType { Id = 148, Name = "Zoologie", Code = "zoology" },
            new DomainType { Id = 200, Name = "Autre", Code = "other" }
        );
    }
}
