// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordsmithHub.Infrastructure.MainDatabase;

#nullable disable

namespace WordsmithHub.Infrastructure.Data.MainDatabase.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260417143505_DomainEntitiesAdded")]
    partial class DomainEntitiesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manages", b =>
                {
                    b.Property<Guid>("DirectCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("DirectCustomerId");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProjectId");

                    b.HasKey("DirectCustomerId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Manages", (string)null);
                });

            modelBuilder.Entity("WordsmithHub.Domain.BankAccountAggregate.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FreelanceId");

                    b.HasIndex("StatusId");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("WordsmithHub.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsEuropeanUnionMember")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FRA",
                            IsEuropeanUnionMember = true,
                            Name = "France"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DEU",
                            IsEuropeanUnionMember = true,
                            Name = "Allemagne"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ESP",
                            IsEuropeanUnionMember = true,
                            Name = "Espagne"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ITA",
                            IsEuropeanUnionMember = true,
                            Name = "Italie"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PRT",
                            IsEuropeanUnionMember = true,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 6,
                            Code = "BEL",
                            IsEuropeanUnionMember = true,
                            Name = "Belgique"
                        },
                        new
                        {
                            Id = 7,
                            Code = "NLD",
                            IsEuropeanUnionMember = true,
                            Name = "Pays-Bas"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CHE",
                            IsEuropeanUnionMember = false,
                            Name = "Suisse"
                        },
                        new
                        {
                            Id = 9,
                            Code = "GBR",
                            IsEuropeanUnionMember = false,
                            Name = "Royaume-Uni"
                        },
                        new
                        {
                            Id = 10,
                            Code = "USA",
                            IsEuropeanUnionMember = false,
                            Name = "États-Unis d’Amérique"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CAN",
                            IsEuropeanUnionMember = false,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AUS",
                            IsEuropeanUnionMember = false,
                            Name = "Australie"
                        },
                        new
                        {
                            Id = 13,
                            Code = "JPN",
                            IsEuropeanUnionMember = false,
                            Name = "Japon"
                        });
                });

            modelBuilder.Entity("WordsmithHub.Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            Name = "Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EUR",
                            Name = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("WordsmithHub.Domain.DirectCustomerAggregate.DirectCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Address_CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PaymentDelay")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("SiretOrSiren")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Address_CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("FreelanceId");

                    b.HasIndex("StatusId");

                    b.ToTable("DirectCustomers", null, t =>
                        {
                            t.Property("Address_CountryId")
                                .HasColumnName("DirectCustomer_Address_CountryId");
                        });
                });

            modelBuilder.Entity("WordsmithHub.Domain.EndCustomerAggregate.EndCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("EndCustomers", (string)null);
                });

            modelBuilder.Entity("WordsmithHub.Domain.FreelanceAggregate.Freelance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Address_CountryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Address_CountryId");

                    b.HasIndex("StatusId");

                    b.ToTable("Freelances", null, t =>
                        {
                            t.Property("Address_CountryId")
                                .HasColumnName("Freelance_Address_CountryId");
                        });
                });

            modelBuilder.Entity("WordsmithHub.Domain.InvoiceAggregate.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerSiretOrSiren")
                        .HasColumnType("text");

                    b.Property<Guid>("DirectCustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FreelanceAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreelanceBankAccountHolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreelanceBankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreelanceBic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreelanceIban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FreelanceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreelancePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreelanceSiret")
                        .HasColumnType("text");

                    b.Property<bool>("FreelanceTaxDeductionExemption")
                        .HasColumnType("boolean");

                    b.Property<bool>("FreelanceVatExemption")
                        .HasColumnType("boolean");

                    b.Property<string>("FreelanceVatNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmountWithVat")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedCurrencyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("WordsmithHub.Domain.LegalStatusAggregate.LegalStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<bool>("TaxDeductionExemption")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<bool>("VatExemption")
                        .HasColumnType("boolean");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("FreelanceId");

                    b.HasIndex("StatusId");

                    b.ToTable("LegalStatuses", (string)null);
                });

            modelBuilder.Entity("WordsmithHub.Domain.OrderLineAggregate.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AppliedUnitPrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceLanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetLanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SourceLanguageId");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("OrderLines", (string)null);
                });

            modelBuilder.Entity("WordsmithHub.Domain.ProjectAggregate.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EndCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EndCustomerId");

                    b.HasIndex("FreelanceId");

                    b.HasIndex("StatusId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("WordsmithHub.Domain.RateAggregate.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DirectCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceLanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetLanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DirectCustomerId");

                    b.HasIndex("FreelanceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SourceLanguageId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TargetLanguageId");

                    b.ToTable("Rates", (string)null);
                });

            modelBuilder.Entity("WordsmithHub.Domain.Service", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Traduction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Relecture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sous-titrage"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Post-édition"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Contrôle qualité"
                        });
                });

            modelBuilder.Entity("WordsmithHub.Domain.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Name = "Actif"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            Name = "Inactif"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Invoice",
                            Name = "Brouillon"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Invoice",
                            Name = "Envoyée"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Invoice",
                            Name = "Payée"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Invoice",
                            Name = "Annulée"
                        },
                        new
                        {
                            Id = 20,
                            Category = "WorkOrder",
                            Name = "En attente"
                        },
                        new
                        {
                            Id = 21,
                            Category = "WorkOrder",
                            Name = "En cours"
                        },
                        new
                        {
                            Id = 22,
                            Category = "WorkOrder",
                            Name = "Terminée"
                        },
                        new
                        {
                            Id = 23,
                            Category = "WorkOrder",
                            Name = "Livrée"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Project",
                            Name = "En cours"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Project",
                            Name = "Terminé"
                        });
                });

            modelBuilder.Entity("WordsmithHub.Domain.TranslationLanguage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("TranslationLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EN",
                            Name = "Anglais"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ES",
                            Name = "Espagnol"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DE",
                            Name = "Allemand"
                        },
                        new
                        {
                            Id = 5,
                            Code = "IT",
                            Name = "Italien"
                        },
                        new
                        {
                            Id = 6,
                            Code = "PT",
                            Name = "Portugais"
                        },
                        new
                        {
                            Id = 7,
                            Code = "NL",
                            Name = "Néerlandais"
                        },
                        new
                        {
                            Id = 8,
                            Code = "RU",
                            Name = "Russe"
                        },
                        new
                        {
                            Id = 9,
                            Code = "JA",
                            Name = "Japonais"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ZH",
                            Name = "Chinois"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AR",
                            Name = "Arabe"
                        },
                        new
                        {
                            Id = 12,
                            Code = "HI",
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = 13,
                            Code = "KO",
                            Name = "Coréen"
                        },
                        new
                        {
                            Id = 14,
                            Code = "TR",
                            Name = "Turc"
                        },
                        new
                        {
                            Id = 15,
                            Code = "PL",
                            Name = "Polonais"
                        });
                });

            modelBuilder.Entity("WordsmithHub.Domain.WorkOrderAggregate.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DirectCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FreelanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DirectCustomerId");

                    b.HasIndex("FreelanceId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("Manages", b =>
                {
                    b.HasOne("WordsmithHub.Domain.DirectCustomerAggregate.DirectCustomer", null)
                        .WithMany()
                        .HasForeignKey("DirectCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Manages_DirectCustomer");

                    b.HasOne("WordsmithHub.Domain.ProjectAggregate.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Manages_Project");
                });

            modelBuilder.Entity("WordsmithHub.Domain.BankAccountAggregate.BankAccount", b =>
                {
                    b.HasOne("WordsmithHub.Domain.FreelanceAggregate.Freelance", null)
                        .WithMany()
                        .HasForeignKey("FreelanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.DirectCustomerAggregate.DirectCustomer", b =>
                {
                    b.HasOne("WordsmithHub.Domain.Country", null)
                        .WithMany()
                        .HasForeignKey("Address_CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordsmithHub.Domain.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.FreelanceAggregate.Freelance", null)
                        .WithMany()
                        .HasForeignKey("FreelanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WordsmithHub.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("DirectCustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressComplement")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Address_Complement");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_City");

                            b1.Property<int>("CountryId")
                                .HasColumnType("integer")
                                .HasColumnName("Address_CountryId");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Address_PostCode");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("StreetInfo")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Address_StreetInfo");

                            b1.HasKey("DirectCustomerId");

                            b1.ToTable("DirectCustomers");

                            b1.WithOwner()
                                .HasForeignKey("DirectCustomerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.EndCustomerAggregate.EndCustomer", b =>
                {
                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.FreelanceAggregate.Freelance", b =>
                {
                    b.HasOne("WordsmithHub.Domain.Country", null)
                        .WithMany()
                        .HasForeignKey("Address_CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WordsmithHub.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("FreelanceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressComplement")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Address_Complement");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_City");

                            b1.Property<int>("CountryId")
                                .HasColumnType("integer")
                                .HasColumnName("Address_CountryId");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Address_PostCode");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("StreetInfo")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Address_StreetInfo");

                            b1.HasKey("FreelanceId");

                            b1.ToTable("Freelances");

                            b1.WithOwner()
                                .HasForeignKey("FreelanceId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.LegalStatusAggregate.LegalStatus", b =>
                {
                    b.HasOne("WordsmithHub.Domain.FreelanceAggregate.Freelance", null)
                        .WithMany()
                        .HasForeignKey("FreelanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.OrderLineAggregate.OrderLine", b =>
                {
                    b.HasOne("WordsmithHub.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.TranslationLanguage", null)
                        .WithMany()
                        .HasForeignKey("SourceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.TranslationLanguage", null)
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.WorkOrderAggregate.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.ProjectAggregate.Project", b =>
                {
                    b.HasOne("WordsmithHub.Domain.EndCustomerAggregate.EndCustomer", null)
                        .WithMany()
                        .HasForeignKey("EndCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordsmithHub.Domain.FreelanceAggregate.Freelance", null)
                        .WithMany()
                        .HasForeignKey("FreelanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.RateAggregate.Rate", b =>
                {
                    b.HasOne("WordsmithHub.Domain.DirectCustomerAggregate.DirectCustomer", null)
                        .WithMany()
                        .HasForeignKey("DirectCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.FreelanceAggregate.Freelance", null)
                        .WithMany()
                        .HasForeignKey("FreelanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.TranslationLanguage", null)
                        .WithMany()
                        .HasForeignKey("SourceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.TranslationLanguage", null)
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordsmithHub.Domain.WorkOrderAggregate.WorkOrder", b =>
                {
                    b.HasOne("WordsmithHub.Domain.DirectCustomerAggregate.DirectCustomer", null)
                        .WithMany()
                        .HasForeignKey("DirectCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.FreelanceAggregate.Freelance", null)
                        .WithMany()
                        .HasForeignKey("FreelanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.InvoiceAggregate.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordsmithHub.Domain.ProjectAggregate.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordsmithHub.Domain.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
