name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        working-directory: ./src/gui
        run: npm ci

      - name: Tests
        working-directory: ./src/gui
        run: npm test

      - name: Build app
        working-directory: ./src/gui
        run: npm run build

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: francois-popieul
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/francois-popieul/wordsmithhub-api:1.1.2

      - name: Build and push Client image
        uses: docker/build-push-action@v6
        with:
          context: ./src/gui
          file: Dockerfile
          push: true
          tags: ghcr.io/francois-popieul/wordsmithhub-client:1.1.2

      - name: SSH deployment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/francois-popieul/wordsmithhub-api:1.1.2
            docker pull ghcr.io/francois-popieul/wordsmithhub-client:1.1.2
            docker compose -f /home/ubuntu/wordsmithhub-prod/compose.prod.yaml up -d --remove-orphans
