name: Deploy to Staging VPS

on:
  push:
    branches: [staging]

jobs:
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yaml

  ci-backend:
    uses: ./.github/workflows/ci-backend.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: [ci-frontend, ci-backend]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: francois-popieul
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: ./src/backend
          file: ./src/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/francois-popieul/wordsmithhub-staging-api:1.1.5
            ghcr.io/francois-popieul/wordsmithhub-staging-api:latest

      - name: Build and push Client image
        uses: docker/build-push-action@v6
        with:
          context: ./src/gui
          file: ./src/gui/Dockerfile
          push: true
          tags: |
            ghcr.io/francois-popieul/wordsmithhub-staging-client:1.1.5
            ghcr.io/francois-popieul/wordsmithhub-staging-client:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.FRONTEND_STAGING_VITE_API_BASE_URL }}

      - name: SSH deployment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/francois-popieul/wordsmithhub-staging-api:latest
            docker pull ghcr.io/francois-popieul/wordsmithhub-staging-client:latest
            docker compose -f /home/ubuntu/wordsmithhub-staging/compose.staging.yaml --env-file /home/ubuntu/wordsmithhub-staging/.env.staging up -d --remove-orphans
